name: 'Composer update'
description: 'Install or update Composer dependencies'
inputs:
  prefer:
    description: 'Prefer lowest or highest versions of dependencies'
    required: false
    default: 'highest'
runs:
  using: 'composite'
  steps:
    - name: Get composer cache directory
      id: composercache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Update project dependencies
      shell: bash
      run: composer update --no-interaction --no-progress --ansi --no-plugins
      if: ${{ inputs.prefer != 'lowest' }}
    - name: Update project dependencies (lowest)
      shell: bash
      run: composer update --no-interaction --no-progress --ansi --no-plugins --prefer-lowest
      if: ${{ inputs.prefer == 'lowest' }}
